<h1 style="text-align: center;">Experiment 1</h1>

<h4> Aim : Introduction to python programming for data analytics</h4>

In [1]:
print(5)

5


In [2]:
a = 3
b = "hi"
c = 2.233

In [3]:
a = 3
b = "hi"
c = 2.233

In [4]:
print(a, b, c)

3 hi 2.233


In [5]:
print(type(a), type(b), type(c))

<class 'int'> <class 'str'> <class 'float'>


In [6]:
a,b,c

(3, 'hi', 2.233)

<h5>           Operator </h5>

In [7]:
n1 = 5
n2 = 6

print(n1 + n2)
print(n1 - n2)
print(n1 * n2)
print(n1 / n2)
print(n1 // n2)
print(n1 % n2)
print(n1 ** n2)

11
-1
30
0.8333333333333334
0
5
15625


<h5>           Condition </h5>

In [8]:
if n1 > n2 :
   print(n1 , ":n1 is big")
elif n1< n2 :
   print(n2, ":n2 is big")
elif (n1 is n2):
   print("Both are equal")

6 :n2 is big


<h5>           Loop  </h5>

In [9]:
for i in range(5):
    print(i) 

0
1
2
3
4


In [10]:
i = 0
while i < 5:
    print(i)
    i += 1

0
1
2
3
4


<h5>           Composite data type </h5>

In [11]:
#mutable : List

arr  = [1,24, "hii", 221.13]
print(arr)

for i in arr:
    print(i)

[1, 24, 'hii', 221.13]
1
24
hii
221.13


In [12]:
#immutable : Tuple

tp = (1,24, "hii", 221.13)
print(tp)

for i in tp:
    print(i)

(1, 24, 'hii', 221.13)
1
24
hii
221.13


In [13]:
# key value pair : Dictionary
kv = {"name":"sai", "age":24, "city":"hyd"}
print(kv)

for k,v in kv.items():
    print(k, ":", v)


{'name': 'sai', 'age': 24, 'city': 'hyd'}
name : sai
age : 24
city : hyd


In [14]:
arr

[1, 24, 'hii', 221.13]

In [15]:
arr[0:-1:2]

[1, 'hii']

<h5>           Function </h5>

In [16]:
def sum (a, b):
   return a+b

sum(2,3) 

5

In [17]:
def rec(n):
   if n< 0:
      print("n should be greater than 0")
   elif n==0 or n==1:
      return 1
   else:
      return n*rec(n-1)

print(rec(5))
      

120


<h5>           Numpy </h5>

In [18]:
!pip install numpy


[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [19]:
import numpy as np

In [20]:
arr = np.array([1,2,3,4,5])

In [21]:
arr

array([1, 2, 3, 4, 5])

In [22]:
arr[1]

2

In [23]:
arr[-1]

5

In [24]:
arr[1:-1]

array([2, 3, 4])

In [25]:
arr[2:]

array([3, 4, 5])

In [26]:
b = np.array([[1,2,3],[4,5, 6],[7,8,9]])

In [27]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
b[0,2]

3

In [29]:
b[0:2, 0]

array([1, 4])

In [30]:
b[1, :]

array([4, 5, 6])

In [31]:
b[1:, 1:]

array([[5, 6],
       [8, 9]])

In [32]:
b.shape

(3, 3)

<h5>           matrix operation </h5>

In [33]:
c = np.array([[1,2,4],[4,5, 6],[6,8,9]])

In [34]:
c

array([[1, 2, 4],
       [4, 5, 6],
       [6, 8, 9]])

In [35]:
b+ c

array([[ 2,  4,  7],
       [ 8, 10, 12],
       [13, 16, 18]])

In [36]:
b-c

array([[ 0,  0, -1],
       [ 0,  0,  0],
       [ 1,  0,  0]])

In [37]:
b*c

array([[ 1,  4, 12],
       [16, 25, 36],
       [42, 64, 81]])

In [38]:
b/c

array([[1.        , 1.        , 0.75      ],
       [1.        , 1.        , 1.        ],
       [1.16666667, 1.        , 1.        ]])

In [39]:
np.dot(b,c)

array([[ 27,  36,  43],
       [ 60,  81, 100],
       [ 93, 126, 157]])

In [40]:
np.transpose(b)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [41]:
np.cross(b,c)

array([[ 2, -1,  0],
       [ 0,  0,  0],
       [ 0, -9,  8]])

In [42]:
np.sin(b)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [43]:
np.exp(b)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [44]:
np.log(b)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])